THIS LOG IS FOR DEBUGGING PURPOSES. THANK YOU.
[Sat Aug  2 15:58:37 2025]: Assigned unique id:1
[Sat Aug  2 15:59:40 2025]: Trying to execute command: manager.write_inspector_labels_x[0].place(50,50)
[Sat Aug  2 15:59:40 2025]: Error executing command: Traceback (most recent call last):
  File "c:\Users\flix8\OneDrive\Dokumente\GitHub\scriptor\main.py", line 66, in on_update
    exec(command,globals())
  File "<string>", line 1, in <module>
TypeError: Place.place_configure() takes from 1 to 2 positional arguments but 3 were given

[Sat Aug  2 15:59:47 2025]: Trying to execute command: manager.write_inspector_labels_x[0].place(x=50,y=50)
[Sat Aug  2 15:59:54 2025]: Trying to execute command: manager.write_inspector_labels_x[0].place(x=30,y=50)
[Sat Aug  2 16:00:00 2025]: Trying to execute command: manager.write_inspector_entries_x[0].place(x=30,y=50)
[Sat Aug  2 16:00:04 2025]: Trying to execute command: manager.write_inspector_entries_x[0].place(x=50,y=50)
[Sat Aug  2 16:00:08 2025]: Trying to execute command: manager.write_inspector_entries_x[0].place(x=90,y=50)
[Sat Aug  2 16:00:44 2025]: Trying to execute command: manager.write_inspector_labels_y[0].place(x=90,y=50)
[Sat Aug  2 16:00:49 2025]: Trying to execute command: manager.write_inspector_labels_y[0].place(x=1500,y=50)
[Sat Aug  2 16:00:52 2025]: Trying to execute command: manager.write_inspector_labels_y[0].place(x=150,y=50)
[Sat Aug  2 16:00:56 2025]: Trying to execute command: manager.write_inspector_labels_y[0].place(x=160,y=50)
[Sat Aug  2 16:01:12 2025]: Trying to execute command: manager.write_inspector_entries_y[0].place(x=200,y=50)
[Sat Aug  2 16:01:18 2025]: Trying to execute command: manager.write_inspector_entries_y[0].place(x=210,y=50)
[Sat Aug  2 16:01:21 2025]: Trying to execute command: manager.write_inspector_entries_y[0].place(x=230,y=50)
[Sat Aug  2 16:01:24 2025]: Trying to execute command: manager.write_inspector_entries_y[0].place(x=220,y=50)
